#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME=$(git symbolic-ref --short HEAD)

# if ! npx --no-install validate-branch-name "$BRANCH_NAME"; then
#   echo "Invalid branch name"
#   exit 1
# fi
